name: 'Add github comment'
description: 'Add a PR status as a comment'
author: 'Bright Network'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  id:
    required: false
    description: 'the id to use for de-duplication. Different from the github comment id'
  body:
    required: false
    description: 'the comment body'
  template-path:
    required: false
    description: 'path to the template to use for the comment body'
  template-var:
    required: false
    description: 'additional variable use during templating'
  skip-comment:
    required: false
    description: 'if this input is set to a non-falsy value, the comment will be skipped. Any previously posted comment with the same id will be deleted'
runs:
  using: 'node24'
  main: 'dist/index.js'
